version: '3.4'
services:
  txautht:
    container_name: txautht
    image: renci/txautht:1.0
    restart: always
    env_file:
      - ./env.docker
    ports:
      - $API_PORT:8080
 
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${IPAM_CONFIG_SUBNET}
