version: "3.4"
services:
  txautht-nginx:
    build:
      context: nginx
    restart: always  
    volumes:
      - $SSL_CERT_DIR:/a
    env_file:
      - ./env.docker
    ports:
      - 443:443
      - 80:80
    depends_on:
      - txautht
